# Generated by Django 3.2.4 on 2021-06-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50, unique=True, verbose_name='book name')),
                ('book_writer', models.CharField(max_length=50, unique=True, verbose_name='book writer')),
                ('year_of_publication', models.IntegerField(max_length=4, verbose_name='year of publication')),
                ('registration_time', models.DateTimeField(auto_now_add=True, verbose_name='registration time')),
                ('update_time', models.DateTimeField(verbose_name='update time')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='ddd')),
            ],
        ),
    ]
