# Generated by Django 3.2.4 on 2021-06-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_year_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='username'),
        ),
    ]
