# Generated by Django 3.2.4 on 2021-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='username',
            field=models.CharField(max_length=50, verbose_name='username'),
        ),
    ]
